import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  async function deleteThemeCookie(formData) {
    "use server";
    cookies().delete("chat-app");
  }

  return (
    <html lang="en">
      <body className={inter.className}></body>
      <nav className="nav">
        <Link href="/">Home</Link>
        <form action={deleteThemeCookie}>
          <button type="submit">Logout</button>
        </form>
      </nav>
      {children}
    </html>
  );
}
